CREATE TABLE EMPLOYEE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64) NOT NULL,
  MIDDLE_NAME VARCHAR(1),
  LAST_NAME VARCHAR(64) NOT NULL,
  BIRTH_DATE DATE NOT NULL,
  EMPLOYMENT_DATE DATE NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CONSTRAINT CHEK_STATUS CHECK(STATUS='1' OR STATUS='0') 
);
